apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: cockroach-database-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cockroach-database-role
subjects:
- kind: ServiceAccount
  name: cockroach-database-sa
  namespace: default
